apiVersion: v1
kind: ConfigMap
metadata:
  name: my-plugin
  namespace: not-argo-ns
data:
  token: "$plugin.myplugin.token" # Alternatively $<some_K8S_secret>:plugin.myplugin.token
  baseUrl: "http://myplugin.plugin-ns.svc.cluster.local."
